	<!-- jQuery -->
	<script src="{{ asset('adminAssets/vendors/jquery/dist/jquery.min.js')}}"></script>
	<!-- Bootstrap -->
	<script src="{{ asset('adminAssets/vendors/bootstrap/dist/js/bootstrap.bundle.min.js')}}"></script>
	<!-- FastClick -->
	<script src="{{ asset('adminAssets/vendors/fastclick/lib/fastclick.js')}}"></script>
	<!-- NProgress -->
	<script src="{{ asset('adminAssets/vendors/nprogress/nprogress.js')}}"></script>
	<!-- bootstrap-progressbar -->
	<script src="{{ asset('adminAssets/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js')}}"></script>
	<!-- iCheck -->
	<script src="{{ asset('adminAssets/vendors/iCheck/icheck.min.js')}}"></script>
	<!-- bootstrap-daterangepicker -->
	<script src="{{ asset('adminAssets/vendors/moment/min/moment.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
	<!-- bootstrap-wysiwyg -->
	<script src="{{ asset('adminAssets/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/jquery.hotkeys/jquery.hotkeys.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/google-code-prettify/src/prettify.js')}}"></script>
	<!-- jQuery Tags Input -->
	<script src="{{ asset('adminAssets/vendors/jquery.tagsinput/src/jquery.tagsinput.js')}}"></script>
	<!-- Switchery -->
	<script src="{{ asset('adminAssets/vendors/switchery/dist/switchery.min.js')}}"></script>
	<!-- Select2 -->
	<script src="{{ asset('adminAssets/vendors/select2/dist/js/select2.full.min.js')}}"></script>
	<!-- Parsley -->
	<script src="{{ asset('adminAssets/vendors/parsleyjs/dist/parsley.min.js')}}"></script>
	<!-- Autosize -->
	<script src="{{ asset('adminAssets/vendors/autosize/dist/autosize.min.js')}}"></script>
	<!-- jQuery autocomplete -->
	<script src="{{ asset('adminAssets/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js')}}"></script>
	<!-- starrr -->
	<script src="{{ asset('adminAssets/vendors/starrr/dist/starrr.js')}}"></script>
	<!-- Custom Theme Scripts -->
	<script src="{{ asset('adminAssets/build/js/custom.min.js')}}"></script>
-------------------------------------------------------------------------------------
	<!-- Datatables -->
	<script src="{{ asset('adminAssets/vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/datatables.net-scroller/js/dataTables.scroller.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/jszip/dist/jszip.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/pdfmake/build/pdfmake.min.js')}}"></script>
	<script src="{{ asset('adminAssets/vendors/pdfmake/build/vfs_fonts.js')}}"></script>
